### ISSUE TITLE
Build status icon should open Github action page

### ISSUE THREAD

**Issue by abhi1693** [StackStorm-Exchange/web#59]

**Comment by armab** [comment]
Do you mean adding a CI status badge to https://github.com/StackStorm-Exchange/web/blob/master/README.md

Should be an easy one, but helpful. PRs are welcome:+1:

**Comment by abhi1693** [comment]
I meant the packs show an icon that takes the user to Circle CI, however, you guys have migrated the CI to Github action. Today a new pack was added `LogicMonitor` and I wanted to check the CI build status. It took me to a 404 page on Circle CI

**Comment by armab** [comment]
Could you clarify where do you see the CircleCI icon?
https://exchange.stackstorm.org/ ?

**Comment by abhi1693** [comment]
Relevant code is at https://github.com/StackStorm-Exchange/web/blob/master/src/components/PackView.jsx#L60


![image](https://user-images.githubusercontent.com/5083532/149222597-241ad235-fa46-49ec-a9b7-3a8f035cbd28.png)

**Comment by cognifloyd** [comment]
Wow. I didn't know about that when we planned the switch to GHA. We need to fix that! Thank you for reporting it.

**Comment by abhi1693** [comment]
@armab @cognifloyd I have raised a PR for you to review
