### ISSUE TITLE
Wrong pack order

### ISSUE THREAD

**Issue by enykeev** [StackStorm-Exchange/web#9]
The packs with capital letter in them appear on the list before the others.

The problem here is that Exchange relies on the order of the packs in the index. Instead, the packs should be sorted alphabetically and case-insensitively on client side.

<img width="1437" alt="screen shot 2016-11-29 at 4 04 07 pm" src="https://cloud.githubusercontent.com/assets/1357357/20703220/7e8970c8-b64d-11e6-9fa3-2bb4cfe808c4.png">

**Comment by Kami** [comment]
Agreed.

Eventually when we have some  time we can also add some simple client based sorting.
